package com.example.poke_android.ui

import com.example.poke_android.data.*

data class UiState(
    val ready: Boolean = false,
    val user: String? = null,
    val busy: Boolean = false,
    val error: String? = null,
    val catalog: Catalog = Catalog.POKEMON,
    val entries: List<Entry> = emptyList(),
    val next: Int? = null,
    val search: String = "",
    val selectedTypes: List<String> = emptyList(),
    val types: List<String> = emptyList(),
    val listBusy: Boolean = false,
    val listError: String? = null,
    val detail: Entry? = null,
    val evolution: EvolutionChain? = null,
    val randomPokemon: Entry? = null,
    val worldRegions: List<Entry> = emptyList(),
    val worldRegion: RegionDetails? = null,
    val favorites: List<Favorite> = emptyList(),
    val profile: Profile? = null,
    val avatars: List<Avatar> = emptyList(),
    val quiz: Quiz? = null,
    val answered: String? = null,
    val score: Int = 0,
    val region: String? = null,
    val stageType: String? = null,
    val gameMessage: String? = null,
    val ranking: Ranking? = null,
    val progress: List<Region> = emptyList(),
    val stageFinished: Boolean = false,
    val stageCorrect: Int = 0,
    val stageTotal: Int = 0,
    val pendingAnswer: String? = null,
    val saveFailed: Boolean = false,
    val questionId: String = "",
)
